#ifndef _ALT_PCIE_QSYS_SIMPLE_LIB_H_
#define _ALT_PCIE_QSYS_SIMPLE_LIB_H_

/************************************************************************
*  File: alt_pcie_qsys_simple_lib.h
*
*  Library for accessing ALT_PCIE_QSYS_SIMPLE devices.
*  The code accesses hardware using WinDriver's WDC library.
*  Code was generated by DriverWizard v10.21.
*
*  Jungo Confidential. Copyright (c) 2011 Jungo Ltd.  http://www.jungo.com
*************************************************************************/

#include "wdc_lib.h"
#include "samples/shared/pci_regs.h"
#include "samples/shared/bits.h"

#ifdef __cplusplus
extern "C" {
#endif

/*************************************************************
  General definitions
 *************************************************************/
/* Default vendor and device IDs */
#define ALT_PCIE_QSYS_SIMPLE_DEFAULT_VENDOR_ID 0x1172 /* Vendor ID */
#define ALT_PCIE_QSYS_SIMPLE_DEFAULT_DEVICE_ID 0xE001 /* Device ID */


/* Address space information struct */
#define MAX_TYPE 8
typedef struct {
    DWORD dwAddrSpace;
    CHAR sType[MAX_TYPE];
    CHAR sName[MAX_NAME];
    CHAR sDesc[MAX_DESC];
} ALT_PCIE_QSYS_SIMPLE_ADDR_SPACE_INFO;

/* Interrupt result information struct */
typedef struct
{
    DWORD dwCounter; /* Number of interrupts received */
    DWORD dwLost;    /* Number of interrupts not yet handled */
    WD_INTERRUPT_WAIT_RESULT waitResult; /* See WD_INTERRUPT_WAIT_RESULT values in windrvr.h */
    DWORD dwEnabledIntType; /* Interrupt type that was actually enabled
                               (MSI/MSI-X/Level Sensitive/Edge-Triggered) */
    DWORD dwLastMessage; /* Message data of the last received MSI/MSI-X
                        (Windows Vista/7); N/A to line-based interrupts) */
} ALT_PCIE_QSYS_SIMPLE_INT_RESULT;
/* TODO: You can add fields to ALT_PCIE_QSYS_SIMPLE_INT_RESULT to store any additional
         information that you wish to pass to your diagnostics interrupt
         handler routine (DiagIntHandler() in alt_pcie_qsys_simple_diag.c) */

/* ALT_PCIE_QSYS_SIMPLE diagnostics interrupt handler function type */
typedef void (*ALT_PCIE_QSYS_SIMPLE_INT_HANDLER)(WDC_DEVICE_HANDLE hDev,
    ALT_PCIE_QSYS_SIMPLE_INT_RESULT *pIntResult);

/* ALT_PCIE_QSYS_SIMPLE diagnostics plug-and-play and power management events handler function type */
typedef void (*ALT_PCIE_QSYS_SIMPLE_EVENT_HANDLER)(WDC_DEVICE_HANDLE hDev,
    DWORD dwAction);

/*************************************************************
  Function prototypes
 *************************************************************/
DWORD ALT_PCIE_QSYS_SIMPLE_LibInit(void);
DWORD ALT_PCIE_QSYS_SIMPLE_LibUninit(void);

WDC_DEVICE_HANDLE ALT_PCIE_QSYS_SIMPLE_DeviceOpen(const WD_PCI_CARD_INFO *pDeviceInfo);
BOOL ALT_PCIE_QSYS_SIMPLE_DeviceClose(WDC_DEVICE_HANDLE hDev);

static BOOL IsItemExists(PWDC_DEVICE pDev, ITEM_TYPE item);
DWORD ALT_PCIE_QSYS_SIMPLE_IntEnable(WDC_DEVICE_HANDLE hDev, ALT_PCIE_QSYS_SIMPLE_INT_HANDLER funcIntHandler);
DWORD ALT_PCIE_QSYS_SIMPLE_IntDisable(WDC_DEVICE_HANDLE hDev);
BOOL ALT_PCIE_QSYS_SIMPLE_IntIsEnabled(WDC_DEVICE_HANDLE hDev);

DWORD ALT_PCIE_QSYS_SIMPLE_EventRegister(WDC_DEVICE_HANDLE hDev, ALT_PCIE_QSYS_SIMPLE_EVENT_HANDLER funcEventHandler);
DWORD ALT_PCIE_QSYS_SIMPLE_EventUnregister(WDC_DEVICE_HANDLE hDev);
BOOL ALT_PCIE_QSYS_SIMPLE_EventIsRegistered(WDC_DEVICE_HANDLE hDev);

DWORD ALT_PCIE_QSYS_SIMPLE_GetNumAddrSpaces(WDC_DEVICE_HANDLE hDev);
BOOL ALT_PCIE_QSYS_SIMPLE_GetAddrSpaceInfo(WDC_DEVICE_HANDLE hDev, ALT_PCIE_QSYS_SIMPLE_ADDR_SPACE_INFO *pAddrSpaceInfo);


const char *ALT_PCIE_QSYS_SIMPLE_GetLastErr(void);

#ifdef __cplusplus
}
#endif

#endif
